### ISSUE TITLE
nginx error when more than two service bodies added to service body parameter

### ISSUE THREAD

**Issue by californiasteve** [radius314/crouton#10]
When I add more than two service bodies (ASCs) I get the 502 error nginx. Works fine with two or less.
https://nafreedom.org/bmlt-tabs-test/

**Comment by radius314** [comment]
what's your shortcode look like in the event of the failure?  what root server?

**Comment by californiasteve** [comment]
[bmlt_tabs service_body="1095,1024,1025,1028"]
https://texasoklahomana.org/main_server

**Comment by radius314** [comment]
could not repro.

**Comment by californiasteve** [comment]
I'm thinking it's something with my hosting provider.

**Comment by radius314** [comment]
a 502 is a bad gateway, what's the server logs say?

**Comment by californiasteve** [comment]
Added this line in my .htaccess file Solved.
<IfModule mod_substitute.c>
SubstituteMaxLineLength 10M
</IfModule>

**Comment by radius314** [comment]
Where did you get the hint to do this?

**Comment by californiasteve** [comment]
From my hosting provider (Siteground)

**Comment by radius314** [comment]
Looks like this was a SiteGround specific issue.  https://www.siteground.com/kb/divi-builder-timeout-warning/

Closing this out.
