### ISSUE TITLE
PHP error when using php 7.2.9

### ISSUE THREAD

**Issue by paulnagle** [radius314/crouton#14]
I see these errors in my wordpress test install using php 7.2.9

```
Warning: Use of undefined constant latitude - assumed 'latitude' (this will throw an Error in a future version of PHP) in /Applications/XAMPP/xamppfiles/apps/wordpress/htdocs/wp-content/plugins/crouton/crouton.php on line 766

Warning: Use of undefined constant longitude - assumed 'longitude' (this will throw an Error in a future version of PHP) in /Applications/XAMPP/xamppfiles/apps/wordpress/htdocs/wp-content/plugins/crouton/crouton.php on line 766
```

https://github.com/radius314/crouton/blob/e92350a11d4de6651d11dbb10cfd83b903ee0717/crouton.php#L766

Think this needs to be changed to include  single quotes around latitude and longitude for later versions of php

`$map = "<a target='_blank' href='https://maps.google.com/maps?q=" . $value['latitude'] . "," . $value['longitude'] . "' id='map-button' class='btn btn-primary btn-xs'><span class='glyphicon glyphicon-map-marker'></span>MAP</a>"; `

**Comment by radius314** [comment]
where are you seeing these errors?  server logs or browser console?

**Comment by paulnagle** [comment]
In the browser. The plugin does load at the very end of the page, but there are a lot of error messages..

<img width="1325" alt="screen shot 2018-09-20 at 21 08 10" src="https://user-images.githubusercontent.com/3714999/45844139-6cae6280-bd19-11e8-97aa-eade72b1a4cf.png">

**Comment by radius314** [comment]
These are server side errors shown in the browser.

**Comment by paulnagle** [comment]
Fixed in latest master
