### ISSUE TITLE
Add ability to ignore formats

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/crouton#2]
Add ability to ignore certain formats, this should be figured into the counts as well

**Comment by pjaudiomv** [comment]
this could really just be implemented as part of #9

**Comment by pjaudiomv** [comment]
There's an undocumented feature, shortcode attribute format_key will only find meetings with single specified format. I'm thinking we can that too and just use custom query.

**Comment by radius314** [comment]
this is available in 2.0.0-beta

**Comment by radius314** [comment]
this needs to be tested as well.

**Comment by pjaudiomv** [comment]
format_key undocumented shortcode works, this will only display meetings that have set format. im not exactly sure how it was susposed to work. it doesnt work with multiple formats seperated by comma. I still think an ignore would be better but this was in original plugin, though undocumented and still undocumented.

**Comment by radius314** [comment]
you would use a custom query to ignore formats

**Comment by pjaudiomv** [comment]
yes got it, so format_key works with one format, which could very well be how it was supposed to work

**Comment by radius314** [comment]
have you verified this works (using custom query to exclude a format)?

**Comment by radius314** [comment]
released in 2.0.0
