### ISSUE TITLE
Emit A Meta Tag With the Root Server URI

### ISSUE THREAD

**Issue by LittleGreenViper** [radius314/crouton#55]
The standard plugin does this:

&lt;meta name="BMLT-Root-URI" content="https://bmlt.newyorkna.org/main_server" /&gt;

It would be great if Crouton and Bread did that, too.

**Comment by radius314** [comment]
This already exists.  The full query is emoted in javascript.

**Comment by LittleGreenViper** [comment]
I'll have to check it out. Nevermind, then.

**Comment by radius314** [comment]
search the page source for `root_server_query`
