### ISSUE TITLE
Tabs not Displaying

### ISSUE THREAD

**Issue by californiasteve** [radius314/crouton#58]
I installed a new 2.1.3 on two different sites and neither are rendering the tabs. Here's a screenshot of the source.
![image](https://user-images.githubusercontent.com/31661648/47396947-a3014800-d6f2-11e8-9fae-e23c8606cb2b.png)

**Comment by californiasteve** [comment]
Same server different themes.

**Comment by pjaudiomv** [comment]
did 2.1.2? work fine

**Comment by pjaudiomv** [comment]
its coming back with a ReferenceError: getMeetings is not defined on line 349
`				"meetings": getMeetings(meetingData, function(item) {
					return item['weekday_tinyint'] === day.toString();
				})`

**Comment by pjaudiomv** [comment]
I think this may be caused by a conflicting plugin

**Comment by pjaudiomv** [comment]
maybe conflicting css?

**Comment by californiasteve** [comment]
It's stopping an iframe from opening. I'm digging some more.

**Comment by californiasteve** [comment]
Eventon plugin was the conflict.

**Comment by pjaudiomv** [comment]
from the source code it looks like you have both bmlt tabbed ui and crouton activated, you should delete the bmlt tabbed ui or at least deactivate it when using crouton
