### ISSUE TITLE
selected dropdown option not always displaying right

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/crouton#64]
the selected dropdown option wasn't always displaying depending on certain characters in service body name. the option would save correctly and work but the selected value wouldn't display on dropdown. this is how bread does it and escaping them should fix this. found this when saving "Martha's Vineyard" didn't like the apostrophe and the selected value would default to the first (in my case Boston). This issue did exist in previous versions and was not newly introduced.

**Comment by radius314** [comment]
Released in 2.2.1
